Pages/AddFinalReview.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using SAM2020.Models;

namespace SAM2020.Pages
{
    public class AddFinalReviewModel : PageModel
    {
        [BindProperty]
        public List<Paper> papersList { get; set; }
        public Dictionary<string, List<Review>> papersReviews {get; set;}

        public async Task<IActionResult> OnGet() {
          string user = HttpContext.Session.GetString("userID");

          if (string.IsNullOrEmpty(user)) {
            return RedirectToPage(Routes.LOGIN);
          }

          int userRole = -1;
          if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userRole"))) {
            userRole = Convert.ToInt32(HttpContext.Session.GetString("userRole"));
          }

          // If the user is not a PCM or Admin, redirect to the main menu
          if (userRole != Roles.PCC & userRole != Roles.ADMIN) {
            return RedirectToPage(Routes.INDEX);
          }

          Reviews reviews = new Reviews();
          Papers papers = new Papers();
          papersReviews = reviews.getPapersReviews();
          papersList = papers.getReviewsPapers();

          return null;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var paperId = Request.Form["paper_id"];
            var reviewText = Request.Form["review_text"];
            var paperStatus = Request.Form["status"];

            if (String.IsNullOrEmpty(reviewText))
            {
                return RedirectToPage(Routes.ADD_FINAL_REVIEW, new { id = 2 });
            }

            Papers papers = new Papers();

            int status = papers.updateReview(paperId, reviewText, paperStatus);

            if (status != -1) {
                //Notify Authorabout paper decision
                Notification notificationManager = new Notification();
                int statusPaper = notificationManager.sendNotifiactionToOneUser("Your paper has been "+(paperStatus=="2"?"approved":"reject"), papers.getAuthorByPaperID(paperId), Convert.ToInt32(HttpContext.Session.GetString("userID")));

                return RedirectToPage(Routes.ADD_FINAL_REVIEW, new { id = 1 });
            }

            return RedirectToPage(Routes.ADD_FINAL_REVIEW, new { id = 3 });
        }
        public async Task<IActionResult> OnPostConflictAsync()
        {
            Reviews reviews = new Reviews();
            Papers papers = new Papers();
            papersReviews = reviews.getPapersReviews();
            var selectedReviewer = Request.Form["selectedReviewer"];
            string paperTitle = Request.Form["paper_title"];
            string paperReference = Request.Form["paper_reference"];
            string conflictMessage = Request.Form["conflict_message"];
            string senderId = HttpContext.Session.GetString("userID");
            string message = @"
              Your review has conflicting views.
              Paper: @paperTitle
              Message: @conflictMessage
              Users: ";

            List<string> users = new List<string>();

            foreach(Review review in papersReviews[paperReference])
            {
              if (Array.IndexOf(selectedReviewer, review.reviewerId) != -1) {
                string username = review.reviewerName + " - " + review.reviewerEmail;
                users.Add(username);
              }

            }

            message = message + String.Join(", ", users.ToArray());;
            message = message.Replace("@paperTitle", paperTitle);
            message = message.Replace("@conflictMessage", conflictMessage);

            if (String.IsNullOrEmpty(selectedReviewer)) {
              return RedirectToPage(Routes.ADD_FINAL_REVIEW, new { id = 5 });
            }

            Notification notification = new Notification();

            int status = notification.notifyConflict(senderId, message, selectedReviewer);

            if (status == -1)
            {
              return RedirectToPage(Routes.ADD_FINAL_REVIEW, new { id = 6 });
            }

            return RedirectToPage(Routes.ADD_FINAL_REVIEW, new { id = 4 });
        }
    }
}

Pages/AssignPapers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using SAM2020.Models;

namespace SAM2020.Pages
{
    public class AssignPapersModel : PageModel
    {
        public List<User> allPcms { get; set; }
        
        public async Task<IActionResult> OnGet() {
          string user = HttpContext.Session.GetString("userID");

          // If the user is not logged in
          if (string.IsNullOrEmpty(user)) {
            return RedirectToPage(Routes.LOGIN);
          }

          int userRole = -1;
          if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userRole"))) {
            userRole = Convert.ToInt32(HttpContext.Session.GetString("userRole"));
          }

          // If the user is not a PCC or Admin, redirect to the main menu
          if (userRole != Roles.PCC & userRole != Roles.ADMIN) {
            return RedirectToPage(Routes.INDEX);
          }

          Users users = new Users();
          allPcms = users.getUsersByRole(Roles.PCM);

          return null;
        }
    }
}

Pages/AssignPapersDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using SAM2020.Models;

namespace SAM2020.Pages
{
    public class AssignPapersDetailModel : PageModel
    {
        [BindProperty]
        public int selectedUserId { get; set; }
        [BindProperty]
        public List<Paper> allPapers { get; set; }
        [BindProperty]
        public List<Paper> userAssignedPapers { get; set; }
        public List<int> userPreselection { get; set; }
        
        public async Task<IActionResult> OnGet() {
          string user = HttpContext.Session.GetString("userID");

          // If the user is not logged in
          if (string.IsNullOrEmpty(user)) {
            return RedirectToPage(Routes.LOGIN);
          }

          int userRole = -1;
          if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userRole"))) {
            userRole = Convert.ToInt32(HttpContext.Session.GetString("userRole"));
          }

          // If the user is not a PCM or Admin, redirect to the main menu
          if (userRole != Roles.PCC & userRole != Roles.ADMIN) {
            return RedirectToPage(Routes.INDEX);
          }

          selectedUserId = Int32.Parse(Request.Query["userid"]);
          Users users = new Users();

          if (!users.isValidPcmUser(selectedUserId)) {
            return RedirectToPage(Routes.ASSIGN_PAPERS);
          }

          Papers papers = new Papers();
          allPapers = papers.getAllPapers();
          userAssignedPapers = papers.getUserAssignedPapers(selectedUserId);
          userPreselection = papers.getUserPreselection(selectedUserId);

          return null;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            Reviews reviews = new Reviews();
            string userId = HttpContext.Session.GetString("userID");
            var selectedPapers = Request.Form["CheckedPapers"];
            string actualUrl = Request.Path;
            selectedUserId = Int32.Parse(Request.Query["userid"]);

            if (String.IsNullOrEmpty(selectedPapers)) {
              return RedirectToPage(Routes.ASSIGN_PAPER_DETAIL, new { id = 3, userId = selectedUserId });
            }

            int result = reviews.createReviews(selectedUserId, selectedPapers);

            if (result == -1) {
                return RedirectToPage(Routes.ASSIGN_PAPER_DETAIL, new { id = 2, userId = selectedUserId });
            } else if (result != -1) {
                //Notify Author he has paper to review
                Notification notificationManager = new Notification();
                int status = notificationManager.sendNotifiactionToOneUser("You have New assigned <a href=\"/MyAssignedPapers\">paper</a> to review", selectedUserId, Convert.ToInt32(HttpContext.Session.GetString("userID")));

            }

            return RedirectToPage(Routes.ASSIGN_PAPER_DETAIL, new { id = 1, userId = selectedUserId });
        }
    }
}

Pages/ControlPanel.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using SAM2020.Models;

namespace SAM2020.Pages
{
    public class ControlPanelModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {
          string user = HttpContext.Session.GetString("userID");

          // If the user is not logged in
          if (string.IsNullOrEmpty(user)) {
            return RedirectToPage(Routes.LOGIN);
          }

          return null;
        }
    }
}

Pages/CreateNotification.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SAM2020.Models;
using Microsoft.AspNetCore.Http;

namespace SAM2020.Pages
{
    public class CreateNotificationModel : PageModel
    {

        [BindProperty]
        public Notification notification { get; set; }
        public List<User> userList { get; set; }

        public async Task<IActionResult> OnGet() 
        {
          string user = HttpContext.Session.GetString("userID");

          if (string.IsNullOrEmpty(user)) {
            return RedirectToPage(Routes.LOGIN);
          }

          int userRole = -1;
          if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userRole"))) {
            userRole = Convert.ToInt32(HttpContext.Session.GetString("userRole"));
          }

          Users users = new Users();
          userList = users.getAllUsers();

          return null;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            Notification notificationManager = new Notification();
            int userID = Convert.ToInt32(HttpContext.Session.GetString("userID"));
            int status = 0;

            if (String.IsNullOrEmpty(notification.message))
            {
              return RedirectToPage(Routes.CREATE_NOTIFICATION, new { id = 3 });
            }

            if (notification.recipientId < 0)
            {
              status = notificationManager.sendNotifiactionAll(notification.message, notification.recipientId, userID);
            } else {
              status = notificationManager.sendNotifiactionToOneUser(notification.message, notification.recipientId, userID);
            }

            if (status == 0)
            {
              return RedirectToPage(Routes.CREATE_NOTIFICATION, new { id = status });
            }

            return RedirectToPage(Routes.CREATE_NOTIFICATION, new { id = 1 });
        }

    }
}

Pages/CreateUser.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using SAM2020.Models;

namespace SAM2020.Pages
{
    public class CreateUserModel : PageModel
    {
        private readonly ILogger<CreateUserModel> _logger;

        [BindProperty]
        public User user { get; set; }
        public CreateUserModel(ILogger<CreateUserModel> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> OnGet()
        {
          string user = HttpContext.Session.GetString("userID");

          if (string.IsNullOrEmpty(user)) {
            return RedirectToPage(Routes.LOGIN);
          }

          int userRole = -1;
          if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userRole"))) {
            userRole = Convert.ToInt32(HttpContext.Session.GetString("userRole"));
          }

          // If the user is not an Admin, redirect to the main menu
          if (userRole != Roles.ADMIN) {
            return RedirectToPage(Routes.INDEX);
          }

          return null;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Admin admin = new Admin();
            int status = admin.createUser(user);

            // To Do: Add validation, if user is valid.
            if (status != -1) {
              return RedirectToPage(Routes.MANAGE_USERS, new { id = 0 });
            }
            else {
              return RedirectToPage(Routes.CREATE_USER, new { id = 0 });
            }
           
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SAM2020.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using SAM2020.Models;

namespace SAM2020.Pages
{
    public class IndexModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {
          string user = HttpContext.Session.GetString("userID");

          // If the user is not logged in
          if (string.IsNullOrEmpty(user)) {
            return RedirectToPage(Routes.LOGIN);
          }

          return null;
        }
    }
}

Pages/Login.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SAM2020.Models;

namespace SAM2020.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public User user { get; set; }

        public void OnGet()
        {
            HttpContext.Session.Clear();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            User userManage = new User();
            int userID = userManage.login(user.userEmail, user.password);
            if (userID <= 0)
            {
                return RedirectToPage(Routes.LOGIN, new { id = 0 });
            }
            else
            {
                HttpContext.Session.SetString("userID", userID.ToString());
                HttpContext.Session.SetString("userName", user.getUserNameByID(userID.ToString()));
                int userRole = userManage.getUserRole(userID.ToString());
                HttpContext.Session.SetString("userRole", userRole.ToString());

                return RedirectToPage(Routes.INDEX);
            }

           
        }
    }
}

Pages/ManageUsers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SAM2020.Models;

namespace SAM2020.Pages
{
    public class ManageUsersModel : PageModel
    {
        public List<User> userList { get; set; }
        public async Task<IActionResult> OnGet() 
        {
          string user = HttpContext.Session.GetString("userID");

          if (string.IsNullOrEmpty(user)) {
            return RedirectToPage(Routes.LOGIN);
          }

          int userRole = -1;
          if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userRole"))) {
            userRole = Convert.ToInt32(HttpContext.Session.GetString("userRole"));
          }

          // If the user is not an Admin, redirect to the main menu
          if (userRole != Roles.ADMIN) {
            return RedirectToPage(Routes.INDEX);
          }

          Admin admin = new Admin();
          userList = admin.getUsers();

          return null;
        }

        public async Task<IActionResult> OnPostDeleteAsync(string selectedUser)
        {
          Admin admin = new Admin();
          int operationResult = admin.deleteUser(selectedUser);

          if (operationResult != -1)
          {
              return RedirectToPage(Routes.MANAGE_USERS, new { id = 1 });
          }

          return RedirectToPage(Routes.MANAGE_USERS, new { id = 2 });
        }

        public async Task<IActionResult> OnPostAsync()
        {
          Admin admin = new Admin();
          User user = new User();
          user.id = Int32.Parse(Request.Form["userid"]);
          user.userEmail = Request.Form["email"];
          user.name = Request.Form["name"];
          user.role = Request.Form["role"];
          user.password = Request.Form["password"];
          int operationResult = admin.modifyUser(user);

          if (operationResult != -1)
          {

                //Notify user his role has been Changed
                Notification notificationManager = new Notification();
                int status = notificationManager.sendNotifiactionToOneUser("Your information was updated by the admin", user.id, Convert.ToInt32(HttpContext.Session.GetString("userID")));
                return RedirectToPage(Routes.MANAGE_USERS, new { id = 4 });

          }

          return RedirectToPage(Routes.MANAGE_USERS, new { id = 2 });
        }
    }
}

Pages/AddFinalReview.cshtml
@page "{id?}"
@model SAM2020.Pages.AddFinalReviewModel
@{
    ViewData["Title"] = "Reviwed Papers";
    var id = RouteData.Values["id"] is null ? -99 : long.Parse(RouteData.Values["id"].ToString());
    var host = "/papers/";
}

<div>
  <h1>Reviwed Papers</h1>
  @if (id == 1)
  {
    <div class="alert alert-success">
        Your review was succesfully recorded.
    </div>
  }
  @if (id == 2)
  {
    <div class="alert alert-danger">
        Review cannot be empty.
    </div>
  }
  @if (id == 3)
  {
    <div class="alert alert-danger">
        Something was wrong saving your review.
    </div>
  }
  @if (id == 4)
  {
    <div class="alert alert-success">
        Conflict succesfully recorded.
    </div>
  }
  @if (id == 5)
  {
    <div class="alert alert-danger">
        Please select at least one reviewer
    </div>
  }
  @if (id == 6)
  {
    <div class="alert alert-danger">
        Something wrong happened submitting the conflict.
    </div>
  }
  @if (Model.papersList.Count == 0)
  {
    <div class="alert alert-primary">
      You don't have any paper assigned yet.
    </div>
  }
  else 
  {
    @foreach (var paper in @Model.papersList)
    {
        {
          var accordionId = "optionsAccordion" + paper.id;
        }
        <div class="card" style="margin-bottom: 15px;">
          <div class="card-body">
            <h5 class="card-title">@paper.title</h5>
            <h6 class="card-subtitle mb-2 text-muted">@paper.topic</h6>
            <p class="card-text"><b>Co-Authors:</b> @paper.coAuthors</p>
            <p class="card-text"><b>Date:</b> @paper.submissionDate</p>
            <p class="card-text"><b>Versions:</b> @paper.version</p>
            <div class="accordion" id="@String.Concat("accordion", @paper.id)">
              <div class="card">
                <div class="card-header" id="headingOne">
                  <h2 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="@String.Concat("#", "collapse1", @paper.id)" aria-controls="collapseOne">
                      Files
                    </button>
                  </h2>
                </div>
                <div id="@String.Concat("collapse1", @paper.id)" class="collapse" aria-expanded="false" aria-labelledby="headingOne" data-parent="@String.Concat("#", "accordion", @paper.id)">
                  <div class="card-body">
                      @{
                        int paperFileNumber = 1;
                      }
                      @foreach (var file in @paper.fileList) {
                        <a
                          href="@String.Concat(host, file)"
                          target="_blank"
                          class="card-link">
                            @String.Concat("Version ", paperFileNumber)
                        </a>
                        {paperFileNumber = paperFileNumber + 1;}
                      }
                  </div>
                </div>
              </div>
              @if (@Model.papersReviews.ContainsKey(@paper.referenceName))
              {
                <div class="card">
                  <div class="card-header" id="headingTwo">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="@String.Concat("#", "collapse2", @paper.id)" aria-expanded="false" aria-controls="collapseTwo">
                        <span>
                          Reviews
                        </span>
                      </button>
                    </h2>
                  </div>
                  <div id="@String.Concat("collapse2", @paper.id)" class="collapse" aria-labelledby="headingTwo" data-parent="@String.Concat("#", "accordion", @paper.id)">
                    <div class="card-body">
                      <div>
                        <!-- Declare User Modal -->
                        <div style="text-align: right; margin-bottom: 10px;">
                          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="@String.Concat("#", "conflictModal", @paper.id)">
                            Declare Conflicts
                          </button>
                        </div>
                        <div class="modal fade" id="@String.Concat("conflictModal", @paper.id)" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <form asp-page-handler="conflict" method="POST" style="display: inline;">
                                <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalLabel">Declare Conflict</h5>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                <div class="modal-body">
                                  Select the reviewers
                                  @foreach (var review in @Model.papersReviews[@paper.referenceName])
                                  {
                                    <div class="form-check">
                                      <input type="checkbox"
                                        value="@review.reviewerId"
                                        class="form-check-input"
                                        name="selectedReviewer"
                                        id="@String.Concat("reviewer", @review.reviewerId)">
                                      <label class="form-check-label" for="@String.Concat("reviewer", @review.reviewerId)">@review.reviewerName - @review.reviewerEmail</label>
                                    </div>
                                  }
                                <div class="form-group">
                                  <label>Message</label>
                                  <textarea name="conflict_message"
                                    rows="5"
                                    placeholder="Add your message here"
                                    style="width: 100%;"></textarea>
                                </div>
                                <input type="hidden" name="paper_reference" value="@paper.referenceName">
                                <input type="hidden" name="paper_title" value="@paper.title">
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                  <button type="submit" class="btn btn-primary">Send</button>
                                </div>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                      @if (@Model.papersReviews.ContainsKey(@paper.referenceName))
                      {
                        @foreach (var review in @Model.papersReviews[@paper.referenceName])
                        {
                          <div class="card">
                            <div class="card-body">
                              <h4 class="lead">@review.reviewerName - @review.editedDate</h4>
                              <hr class="my-4">
                              <p>@review.text</p>
                            </div>
                          </div>
                        }
                      }
                      else {
                        <div class="alert alert-danger">
                          Reviews not provided yet.
                        </div>
                      }
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="card-header" id="headingThree">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="@String.Concat("#", "collapse3", @paper.id)" aria-expanded="false" aria-controls="collapseThree">
                        <span>
                          Final Review
                        </span>
                      </button>
                    </h2>
                  </div>
                  <div id="@String.Concat("collapse3", @paper.id)" class="collapse" aria-labelledby="headingThree" data-parent="@String.Concat("#", "accordion", @paper.id)">
                    <div class="card-body">
                      @if (String.IsNullOrEmpty(@paper.finalReview))
                      {
                        <div class="alert alert-danger">
                          Review not provided yet.
                        </div>
                      }
                      else {
                        <p>
                          @paper.finalReview
                        </p>
                      }
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="card-header" id="headingFour">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="@String.Concat("#", "collapse4", @paper.id)" aria-expanded="false" aria-controls="collapseFour">
                        @if (String.IsNullOrEmpty(@paper.finalReview))
                        {
                          <span>
                            Add Final Review
                          </span>
                        } else {
                          <span>
                            Update Final Review
                          </span>
                        }                       
                      </button>
                    </h2>
                  </div>
                  <div id="@String.Concat("collapse4", @paper.id)" class="collapse" aria-labelledby="headingFour" data-parent="@String.Concat("#", "accordion", @paper.id)">
                    <div class="card-body">
                      <form method="post">
                        <div>
                          <input type="hidden" name="paper_id" value="@paper.id">
                        </div>
                        <div>
                          <div>
                            <div class="form-group col-md-4">
                              <label for="status">Decision</label>
                              <select name="status" class="form-control">
                                <option value="2">Approve</option>
                                <option vallue="3">Reject</option>
                              </select>
                            </div>
                            <textarea name="review_text" rows="5" placeholder="Add your review here" style="width: 100%;"></textarea>
                          </div>
                          <button type="submit" class="btn btn-success">Submit</button> 
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              }
            </div>
          </div>
        </div>
    }
  }
</div>

Pages/AssignPapers.cshtml
@page "{id?}"
@model SAM2020.Pages.AssignPapersModel
@{
    ViewData["Title"] = "Assign Papers";
    List<Paper> preselectedObjects = new List<Paper>();
    var id = RouteData.Values["id"] is null ? -99 : long.Parse(RouteData.Values["id"].ToString());
    int userId = Int32.Parse(HttpContext.Session.GetString("userID"));
    var BASE_URL = "/assignpapersdetail?userid="; 
    
}

@if (id == 1)
{
    <div class="alert alert-success">
        <strong>Your preselection has been recorded.
    </div>
}else if (id == 2)
{
    <div class="alert alert-warning">
        <strong>Sorry, there was something wrong saving your selection.
    </div>
} else if (id == 3)
{
    <div class="alert alert-info">
        <strong>Please select at least one paper.
    </div>
}

<h1>Assign Papers for review</h1>
<div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Option</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var user in @Model.allPcms)
      {
        <tr>
          <th scope="row">@user.id</th>
          <td>@user.name</td>
          <td>@user.userEmail</td>
          <td>
            <a href="@String.Concat(BASE_URL, user.id)" class="card-link">Assign Papers</a>
          </td>
        </tr>
      }
    </tbody>
  </table>
</div>